kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: syndesis-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syndesis-operator
subjects:
  - kind: ServiceAccount
    name: syndesis-operator
    namespace: syndesis-operator