apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syndesis-operator
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get
  - apiGroups:
      - console.openshift.io
    resources:
      - consolelinks
    verbs:
      - get
      - create
      - update
      - delete