apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syndesises.syndesis.io
  labels:
    app: syndesis
spec:
  group: syndesis.io
  names:
    kind: Syndesis
    listKind: SyndesisList
    plural: syndesises
# TODO:  Use "syndeses" when upgrading the CRD version
    singular: syndesis
  scope: Namespaced
  version: v1alpha1
  additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The syndesis phase
      name: Phase
      type: string
    - JSONPath: .status.version
      description: The syndesis version
      name: Version
      type: string
# TODO: Enable when upgrading the CRD version
#    subresources:
#      status: {}
